### ISSUE TITLE
Drive GPIO Pins with Sonic Pi

### ISSUE THREAD

**Issue by hanuman1** [vielmetti/all-systems-go-sonicpi-on-arm64#11]
The idea is that Sonic Pi should be able to switch on LED by the pulse of the music.

**Comment by frzb** [comment]
May be related issue: https://github.com/samaaron/sonic-pi/issues/124

**Comment by stefanmek** [comment]
We can't use a GPIO directly from Sony Pi fault of funding.  But we can work around it by using Sonic Pi to produce an OSC output, and then sent and picked up by Python script to drive the LED with GPIO zero. 
We require Python 3 into YOCTO.

**Comment by stefanmek** [comment]
```
# Welcome to Sonic Pi v3.1
use_osc "192.168.1.18", 12345

live_loop :flibble do
  sample :bd_haus, rate: 1
  osc "Hello/world"
  sleep 1
end

```
we were able to send the OSC package over the network on the beat of the music
