### ISSUE TITLE
Connect Sonic Pi to Raspberry Pi

### ISSUE THREAD

**Issue by hanuman1** [vielmetti/all-systems-go-sonicpi-on-arm64#7]
We would like to connect Sonic Pi to Raspberry Pi!

https://github.com/samaaron/sonic-pi

**Comment by vielmetti** [comment]
Sonic Pi allows you simply convert code into music.

DJ Herve "on the ones and twos"

**Comment by vielmetti** [comment]
We have some music loaded in #21

**Comment by vielmetti** [comment]
It was a fun hacking day in Berlin!
