### ISSUE TITLE
Create correct Github permissions

### ISSUE THREAD

**Issue by vielmetti** [vielmetti/all-systems-go-sonicpi-on-arm64#9]
Set up Github so that the appropriate people (perhaps all?) can manage this.

**Comment by hanuman1** [comment]
This issue is resolved. i just look on StackOverflow.

https://stackoverflow.com/questions/7920320/adding-a-collaborator-to-my-free-github-account

**Comment by vielmetti** [comment]
Will be 100% done when Ola takes his invite.
